"""Real-model end-to-end tests (PLAN.md: ``test_integration.py``, skippable).

Boots a real uvicorn server in a background thread with the *real* pocket-tts
engine (weights download on the first run, then served from the HF cache) and
drives it over real HTTP with ``httpx`` — the full stack, no mocks. The
OpenAI-compat surface is asserted directly (error payloads carry the
``invalid_request_error`` shape, content types, chunked streaming).

Skipped unless ``POCKET_TTS_E2E=1`` so the default ``uv run pytest`` (fast,
offline, mocked) is unaffected:

    uv sync --extra engine               # install pocket-tts (CPU torch)
    POCKET_TTS_E2E=1 uv run pytest -m e2e -v
"""

from __future__ import annotations

import io
import os
import socket
import threading
import time
import wave
from collections.abc import Iterator

import httpx
import pytest

pytestmark = [
    pytest.mark.e2e,
    pytest.mark.skipif(
        os.environ.get("POCKET_TTS_E2E") != "1",
        reason="real-model e2e is opt-in: run with POCKET_TTS_E2E=1",
    ),
]

_SAMPLE_RATE = 24000
_SPEECH_URL = "/v1/audio/speech"


def _free_port() -> int:
    s = socket.socket()
    s.bind(("127.0.0.1", 0))
    port = s.getsockname()[1]
    s.close()
    return port


@pytest.fixture(scope="session")
def live_server() -> Iterator[str]:
    """A real uvicorn app with the real pocket-tts engine, ready when health=ok."""
    try:
        import pocket_tts  # noqa: F401  (engine extra)
    except ImportError:
        pytest.skip("pocket-tts not installed; run `uv sync --extra engine`")

    import uvicorn

    from pocket_tts_openai.config import Config
    from pocket_tts_openai.server import create_app

    cfg = Config(host="127.0.0.1", port=0, idle_unload_s=0)  # keep model resident
    app = create_app(cfg)  # engine=None -> background load thread
    port = _free_port()
    server = uvicorn.Server(
        uvicorn.Config(app, host="127.0.0.1", port=port, log_level="warning")
    )
    thread = threading.Thread(target=server.run, daemon=True)
    thread.start()

    base = f"http://127.0.0.1:{port}"
    deadline = 300.0  # first run may download weights; warm cache is ~20 s
    t0 = time.monotonic()
    ready = False
    while time.monotonic() - t0 < deadline:
        try:
            if httpx.get(f"{base}/health", timeout=10.0).json().get("status") == "ok":
                ready = True
                break
        except httpx.HTTPError:
            time.sleep(2)
            continue
        time.sleep(2)
    if not ready:
        server.should_exit = True
        pytest.fail("server did not become ready within 300 s")

    yield base

    server.should_exit = True
    thread.join(timeout=15)


@pytest.fixture(scope="session")
def client(live_server) -> Iterator[httpx.Client]:
    with httpx.Client(base_url=live_server, timeout=30.0) as c:
        yield c


def _wav_stats(content: bytes) -> tuple[int, float, float]:
    """Parse a 44-byte-header WAV: (frames, rms, peak)."""
    import numpy as np

    with wave.open(io.BytesIO(content), "rb") as w:
        assert w.getnchannels() == 1
        assert w.getframerate() == _SAMPLE_RATE
        frames = w.getnframes()
        raw = w.readframes(frames)
    a = np.frombuffer(raw, dtype=np.int16).astype(np.float32) / 32768.0
    return frames, float(np.sqrt((a**2).mean())), float(np.abs(a).max())


def test_e2e_speech_wav(client):
    """POST /v1/audio/speech -> wav over the live HTTP stack (whole path, no mocks)."""
    r = client.post(
        _SPEECH_URL,
        json={"model": "tts-1", "voice": "alloy",
              "input": "End to end test one: this audio was generated by the entire server stack."},
    )
    assert r.status_code == 200
    assert r.headers["content-type"].startswith("audio/wav")
    frames, rms, peak = _wav_stats(r.content)
    assert len(r.content) == 44 + frames * 2
    assert 0.5 <= frames / _SAMPLE_RATE <= 20.0  # sane duration
    assert rms > 0.01 and peak > 0.05  # real speech, not silence


def test_e2e_speech_pcm_raw(client):
    """POST /v1/audio/speech -> raw s16le PCM over the live stack."""
    r = client.post(
        _SPEECH_URL,
        json={"model": "gpt-4o-mini-tts", "voice": "shimmer",
              "input": "End to end test two, raw pcm output.", "response_format": "pcm"},
    )
    assert r.status_code == 200
    assert r.headers["content-type"].startswith("audio/pcm")
    assert len(r.content) % 2 == 0
    assert len(r.content) >= _SAMPLE_RATE  # at least ~1 s
    import numpy as np

    a = np.frombuffer(r.content, dtype=np.int16).astype(np.float32) / 32768.0
    assert float(np.sqrt((a**2).mean())) > 0.01


def test_e2e_models_list(client):
    ids = {m["id"] for m in client.get("/v1/models").json()["data"]}
    assert {"tts-1", "tts-1-hd", "gpt-4o-mini-tts"} <= ids


def test_e2e_unknown_model_and_voice_400(client):
    """Errors carry the OpenAI shape (error.type=invalid_request_error, 400)."""
    r = client.post(_SPEECH_URL, json={"model": "nope", "voice": "alloy", "input": "hi"})
    assert r.status_code == 400
    assert r.json()["error"]["type"] == "invalid_request_error"

    r = client.post(_SPEECH_URL, json={"model": "tts-1", "voice": "not-a-voice", "input": "hi"})
    assert r.status_code == 400
    assert r.json()["error"]["type"] == "invalid_request_error"


def test_e2e_health_reports_ok(client):
    body = client.get("/health").json()
    assert body["status"] == "ok"
    assert body["loaded"] is True
    assert body["idle_unload_s"] == 0


def test_e2e_streaming_wav_chunked(client):
    """The private stream=true extension streams wav in real chunks (size-less
    header + transfer-encoding chunked) and reassembles to a valid WAV body."""
    with client.stream(
        "POST",
        _SPEECH_URL,
        json={"input": "Streaming end to end test.", "voice": "alloy", "stream": True},
    ) as r:
        assert r.status_code == 200
        assert r.headers["content-type"].startswith("audio/wav")
        assert r.headers.get("transfer-encoding") == "chunked"
        chunks = [c for c in r.iter_bytes()]
        body = b"".join(chunks)
    assert len(chunks) > 1  # actually streamed, not buffered whole-file
    assert body.startswith(b"RIFF")
    assert len(body) > 44 and (len(body) - 44) % 2 == 0


def test_e2e_streaming_aac_chunked(client):
    """The private stream=true extension also streams compressed formats: aac
    is encoded through ffmpeg live and arrives chunked with ADTS sync words."""
    if __import__("shutil").which("ffmpeg") is None:
        pytest.skip("ffmpeg not installed (needed for the aac streaming path)")
    with client.stream(
        "POST",
        _SPEECH_URL,
        json={
            "input": "Streaming compressed output end to end test.",
            "voice": "alloy",
            "stream": True,
            "response_format": "aac",
        },
    ) as r:
        assert r.status_code == 200
        assert r.headers["content-type"].startswith("audio/aac")
        assert r.headers.get("transfer-encoding") == "chunked"
        chunks = [c for c in r.iter_bytes()]
        body = b"".join(chunks)
    assert len(chunks) > 1  # actually streamed, not buffered whole-file
    assert body[0] == 0xFF and (body[1] & 0xF0) == 0xF0  # ADTS sync word 0xFFF
    assert len(body) > 100

